//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDVN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CDVN()
        {
            this.Lichhens = new HashSet<Lichhen>();
            this.Thongbaos = new HashSet<Thongbao>();
            this.Yeucaus = new HashSet<Yeucau>();
            this.Ykiens = new HashSet<Ykien>();
        }
    
        public string ID_CD { get; set; }
        public string HoTenCD { get; set; }
        public Nullable<System.DateTime> NgaySinhCD { get; set; }
        public string DiaChi_CD { get; set; }
        public string TT_hn { get; set; }
        public string GioiTinh { get; set; }
        public string Email_CD { get; set; }
        public string SDT_CD { get; set; }
        public string ID_Chuho { get; set; }
        public string TATS { get; set; }
        public byte[] Anh { get; set; }
        public Nullable<int> Noti_count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lichhen> Lichhens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thongbao> Thongbaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yeucau> Yeucaus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ykien> Ykiens { get; set; }
    }
}
