//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreeTime
    {
        public int ID_FreeTime { get; set; }
        public string ID_CQTQ { get; set; }
        public Nullable<System.TimeSpan> Start_time { get; set; }
        public Nullable<System.TimeSpan> End_time { get; set; }
        public Nullable<int> Max_per { get; set; }
    
        public virtual CQTQ CQTQ { get; set; }
    }
}
