//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lichhen
    {
        public int ID_Lichhen { get; set; }
        public string ID_CD { get; set; }
        public string ID_CQTQ { get; set; }
        public string Time { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Date_hen { get; set; }
        public Nullable<System.DateTime> TG { get; set; }
    
        public virtual CQTQ CQTQ { get; set; }
        public virtual CDVN CDVN { get; set; }
    }
}
