//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PBL3 : DbContext
    {
        public PBL3()
            : base("name=PBL3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LDVN> LDVNs { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<Nhiemvu> Nhiemvus { get; set; }
        public virtual DbSet<Quyenhan> Quyenhans { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Thongbao> Thongbaos { get; set; }
        public virtual DbSet<Ykien> Ykiens { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Yeucau> Yeucaus { get; set; }
        public virtual DbSet<CQTQ> CQTQs { get; set; }
        public virtual DbSet<Lichhen> Lichhens { get; set; }
        public virtual DbSet<FreeTime> FreeTimes { get; set; }
        public virtual DbSet<CDVN> CDVNs { get; set; }
    }
}
