//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yeucau
    {
        public int ID_Yeucau { get; set; }
        public string ID_1 { get; set; }
        public string ID_2 { get; set; }
        public Nullable<System.DateTime> Date_sent { get; set; }
        public string Title { get; set; }
        public string ND { get; set; }
        public Nullable<bool> Solved { get; set; }
        public Nullable<bool> Accepted { get; set; }
    
        public virtual CQTQ CQTQ { get; set; }
        public virtual CDVN CDVN { get; set; }
    }
}
